// TEST DATA

export const GET_TEST_DATA = 'GET_TEST_DATA';
export const STORE_TEST_DATA = 'STORE_TEST_DATA';
export const UPDATE_TEST_DATA = 'UPDATE_TEST_DATA';
export const DELETE_TEST_DATA = 'DELETE_TEST_DATA';